export const CONTACT = {
  addressLine1: '40 Old Ferry Road',
  addressLine2: 'Lowell, MA 01854',
  mailingLine1: '40 Old Ferry Road',
  mailingLine2: 'Lowell, MA 01854',
  phoneHref: 'tel:+19787881250',
  phoneLabel: '+1 978-788-1250',
  faxLabel: '',
  emailHref: 'mailto:info@lasamedical.org',
  emailLabel: 'info@lasamedical.org',
  clinicAdminEmailHref: 'mailto:clinicadmin@lasamedical.org',
  clinicAdminEmailLabel: 'clinicadmin@lasamedical.org',
  paypalDonateUrl: '',
  volunteerFormUrl: '',
  facebookUrl: 'https://m.facebook.com/loveallserveallne/',
  mapsEmbedUrl: 'https://www.google.com/maps?q=40+Old+Ferry+Road,+Lowell,+MA+01854&output=embed',
  mapsOpenUrl: 'https://maps.app.goo.gl/b16FkqyKXTAioZb37',
  mapsAppleUrl: 'https://maps.apple.com/?q=40+Old+Ferry+Road,+Lowell,+MA+01854',
};
