import { privacyPageEn } from './privacyNoticeEn';

export const en = {
  lang: 'en',
  otherLang: 'es',
  otherLangLabel: 'Español',
  otherLangPath: '/es',
  siteName: 'LASA Medical Foundation',
  shortName: 'LASA Medical Foundation',
  motto: 'Love All, Serve All',
  paths: {
    home: '/en',
    clinic: '/en/clinic',
    team: '/en/team',
    contact: '/en/contact',
    donate: '/en/donate',
    schedule: '/en/schedule',
    scheduleLookup: '/en/schedule/lookup',
    privacy: '/en/privacy',
    splash: '/',
  },
  nav: [
    { id: 'about', label: 'About Us', to: '/en' },
    { id: 'clinic', label: 'Clinic', to: '/en/clinic' },
    { id: 'book', label: 'Book', to: '/en/schedule' },
    { id: 'contact', label: 'Contact Us', to: '/en/contact' },
    { id: 'donate', label: 'Getting Involved', to: '/en/donate', emphasize: true },
  ],
  splash: {
    title: 'LASA Medical Foundation',
    mission:
      'LASA Medical Foundation is a Massachusetts-based nonprofit that provides free and low-cost, volunteer-driven healthcare to underserved populations, with no service contingent on a patient’s ability to pay or insurance status.',
    phoneLabel: 'Phone',
    enterEnglish: 'Click here to enter English website',
    enterSpanish: 'Oprima aquí para español',
  },
  about: {
    title: 'About Us',
    lede: 'Love All, Serve All.',
    teamCta: 'Meet the Team',
    paragraphs: [
      'LASA Medical Foundation is a Massachusetts-based 501(c)(3) nonprofit organized to provide free and low-cost healthcare to underserved people through a volunteer-driven clinic. No service is contingent on a patient’s ability to pay or insurance status.',
      'The clinic offers non-emergency primary care for acute and chronic conditions. Volunteer physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and community members staff each clinic day without salaries, so as much support as possible goes to patient care.',
      'Many of those volunteers come from the Lowell community we serve. “Love All, Serve All” is both our motto and the way the clinic operates: people give their time because they want neighbors to have a place to turn for care.',
      'We are grateful to every clinician, supporter, and partner who keeps the doors open. If you would like to help, you can contact us at info@lasamedical.org or use the Getting Involved page.',
    ],
  },
  team: {
    title: 'Meet the Team',
    lede: 'The clinic is led by a volunteer board, medical director, and administrator, with visiting clinicians on each clinic day.',
    boardTitle: 'Board Members',
    board: [
      'Ramesh Razdan',
      'Dr. Suman Koganti, MD',
      'Dr. Anasuya Gunturi, MD',
      'Dr. Swapna Putta, MD',
      'Dr. Sanjay Shah, MD',
    ],
    leadership: [
      { role: 'Medical Director', name: 'Dr. Usha Rallapalli' },
      { role: 'Clinic Administrator', name: 'Vijay Sarathy' },
    ],
    thanksTitle: 'With gratitude',
    thanksIntro: 'We thank our partners for supporting clinic operations.',
    memberOf: 'We are a member of',
    back: 'Back to About Us',
  },
  hours: {
    title: 'Hours',
    intro:
      'Standing remote and in-person hours will be posted here as they are confirmed. Specific upcoming clinic days are listed on the schedule.',
    rows: [
      { label: 'Remote by phone', value: 'To be confirmed' },
      { label: 'In-person', value: 'To be confirmed' },
    ],
    scheduleIntro: 'See published clinic days and claim a limited spot.',
    scheduleCta: 'Book a clinic day',
  },
  donate: {
    title: 'Getting Involved',
    lede: 'Support the clinic through a gift, your time, supplies, or a community partnership.',
    button: 'Getting Involved',
    donation: {
      title: 'Make a Donation',
      body: 'Your gift helps volunteer clinicians provide free care in Lowell.',
      button: 'Donate',
      note: 'PayPal checkout will be connected here next.',
    },
    volunteer: {
      title: 'Volunteer',
      body: 'Join volunteer clinicians and community members at the free medical clinic.',
      button: 'Volunteer',
      note: 'A volunteer form will be connected here soon.',
    },
    supplies: {
      title: 'Donate Medical Supplies',
      body: 'To donate medical supplies, contact Vijay Sarathy, Clinic Administrator.',
    },
    partner: {
      title: 'Become a Community Partner',
      body: 'To become a community partner, contact Vijay Sarathy, Clinic Administrator.',
    },
  },
  clinic: {
    heroTitle: 'The Clinic',
    motto: 'Love All, Serve All',
    intro:
      'A volunteer-run clinic offering free primary care to people who are uninsured or cannot afford medical care.',
    subnav: [
      { id: 'services', label: 'Services' },
      { id: 'hours', label: 'Hours' },
      { id: 'location', label: 'Location' },
      { id: 'contact', label: 'Contact' },
      { id: 'privacy', label: 'Privacy' },
      { id: 'schedule', label: 'Schedule' },
      { id: 'donate', label: 'Getting Involved' },
    ],
    paragraphs: [
      'We provide non-emergency care for both acute and chronic medical conditions. The clinic is staffed by volunteer physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and other support staff.',
      '"Love All, Serve All" summarizes the operational principles of our clinic. We are grateful for the chance to provide free medical care to those in need.',
      'Lasa Medical Foundation Inc. is a 501(c)(3) nonprofit organization. To keep expenses as low as possible, we do not have any salaried employees at the medical clinic. Everyone who works at this clinic does so as a non-paid volunteer.',
      'Many of the wonderful volunteers who work at our clinic come from the local community that we serve. Highly skilled medical professionals — physicians, nurse practitioners, physician assistants, registered nurses, and physical therapists — volunteer their time alongside community members who share LASA’s commitment to Love All, Serve All.',
    ],
  },
  operate: {
    title: 'How we operate the Clinic',
    paragraphs: [
      'Much of the assistance we need to operate the Clinic is provided by the physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and all the other support staff who volunteer their time to serve the patients who come to our clinic. We know that the Clinic will be supported by people who of their own accord are moved to provide assistance.',
      'We appreciate all the generosity of our volunteers as well as the many private and institutional donors who make this work possible.',
      'If you would like to help the Lasa Medical Foundation Inc. in some way, you can contact us at info@lasamedical.org.',
    ],
  },
  services: {
    title: 'Services',
    intro:
      'The Lasa Medical Foundation Inc. provides non-urgent and non-emergency primary care services for uninsured individuals who cannot afford the cost of medical care. Remote visits by phone or video and in-person on-site visits are offered according to the clinic schedule. Physical therapy, optometry, mental health, and dental referral support may be available on selected clinic days. Please see the clinic schedule for details.',
    treatTitle: 'Examples of some conditions that we treat',
    treat: [
      'Diabetes',
      'Sore throat / Cough / Cold / Flu',
      'Ear infections / Wax (cerumen) impacted in the ears',
      'Skin conditions',
      'Urine / bladder infections',
      'High blood pressure / High cholesterol',
      'Heartburn',
      'Children with dermatologic and ENT (ear, nose, throat) conditions',
      'Mental health conditions like stress, depression, and anxiety',
      'Eye conditions / Vision exams for prescriptions',
      'Physical therapy',
      'Dental care — preventive and issues impacting general health',
    ],
    cannotTitle: 'Examples of conditions that we cannot treat',
    cannot: [
      'Emergency procedures of any kind',
      'Trauma or injuries that need x-rays',
      'Bleeding problems',
      'Immunizations, TB (tuberculosis bacillus) test, OB/GYN',
      'Disability, DMV, physical examination clearance forms, insurance forms',
      'Patients needing urgent labs',
      'Conditions requiring imaging — MRI / CT',
      'Pap smears',
      'STD / STI — refer these patients to Planned Parenthood or the County Health Department',
      'STD screening',
    ],
  },
  location: {
    title: 'Location',
    clinicName: 'LASA Medical Foundation',
    drivingTitle: 'Driving Address',
    mailingTitle: 'Mailing Address',
    phoneLabel: 'Phone',
    directionsTitle: 'Directions',
    directionsIntro:
      'We are located at 40 Old Ferry Road, Lowell, MA 01854. Use the map below for turn-by-turn directions, or open the location in Google Maps or Apple Maps.',
    parkingTitle: 'Parking',
    parking: 'Parking available on-site.',
    openMaps: 'Open in Google Maps',
    openAppleMaps: 'Open in Apple Maps',
  },
  contact: {
    title: 'Contact Us',
    emergency:
      'If you are experiencing a medical or psychiatric emergency, please call 911 or, if possible, go to the Emergency Department nearest to your location.',
    body:
      'You can contact us by calling our main phone number or by sending an email to the address below. For voice mails, please be sure to leave a call-back number and spell out your name clearly. For emails, please include your name, email, phone, subject, and the message. Please be advised that voice mails or emails are NOT reviewed immediately. They will be attended to only on the next clinic day. There will likely be significant delays in getting back to your message.',
    emailLabel: 'Email',
    inquiryLine: 'Reach out for general inquiries.',
  },
  privacyTeaser: {
    title: 'Privacy',
    paragraphs: [
      'Your protected health information (PHI) is health information that contains identifiers, such as your name, Social Security number, or other information that reveals who you are. For example, your medical record is PHI because it includes your name and other identifiers.',
      'By law, we must (1) protect the privacy of your PHI, (2) tell you about your rights and our legal duties with respect to your PHI, and (3) tell you about our privacy practices and follow our notice currently in effect.',
      'We take these responsibilities seriously and will take appropriate steps to safeguard the privacy of your PHI. Read our full Notice of Privacy Practices for details.',
    ],
    cta: 'Privacy Practices',
  },
  privacyPage: privacyPageEn,
  schedulePage: {
    title: 'Schedule',
    comingSoon: 'Coming Soon...',
    intro:
      'Upcoming clinic days are listed below. Capacity is limited. Claiming a spot holds it while you verify your email.',
    empty: 'No upcoming clinic days are published yet.',
    emptyNote: 'Please check back later, or contact us for the latest clinic dates and hours.',
    error: 'The schedule could not be loaded. Please try again shortly.',
    back: 'Back to the clinic',
    backToList: 'All clinic days',
    lookupCta: 'Check a booking',
    spots: '{n} of {total} spots left',
    full: 'This clinic day is fully booked',
    alreadyBooked: 'This email already has a booking for this clinic day.',
    details: 'View details',
    bookTitle: 'Claim a spot',
    emailLabel: 'Email',
    sendCode: 'Send verification code',
    sending: 'Sending code…',
    otpLabel: '6-digit code',
    otpHelp: 'Enter the code we sent to your email. It expires in a few minutes.',
    verify: 'Verify code',
    verifying: 'Verifying…',
    resend: 'Resend code',
    nameLabel: 'Full name',
    phoneLabel: 'Phone',
    consentLabel:
      'I consent to LASA Medical Foundation storing this contact information to complete my clinic booking.',
    confirmSpot: 'Confirm booking',
    confirming: 'Confirming…',
    successTitle: 'Your spot is confirmed',
    confirmationLabel: 'Confirmation code',
    emailSent: 'A confirmation email is on the way.',
    emailFailed: 'Your booking is confirmed, but the confirmation email could not be sent. Save this code.',
    holdNote: 'This hold expires at {time}. Finish the steps below to keep the spot.',
    notFound: 'This clinic day is not available.',
    lookupTitle: 'Check your booking',
    lookupIntro: 'Enter the confirmation code and the email used to book.',
    codeLookupLabel: 'Confirmation code',
    findBooking: 'Find booking',
    looking: 'Looking up…',
    lookupMissing: 'No matching confirmed booking was found.',
    statusLabel: 'Status',
    patientLabel: 'Name',
    eventLabel: 'Clinic day',
  },
  footer: {
    linksTitle: 'Quick Links',
    donateIntro: 'Give, volunteer, donate supplies, or partner with the clinic.',
    legal:
      'Lasa Medical Foundation is a federally recognized 501(c)(3) non-profit organization. EIN: 42-2270643',
  },
};
