import { privacyPageEn } from './privacyNoticeEn';

export const en = {
  lang: 'en',
  otherLang: 'es',
  otherLangLabel: 'Español',
  otherLangPath: '/es',
  siteName: 'LASA Medical Foundation',
  shortName: 'LASA Medical Foundation',
  motto: 'Love All, Serve All',
  paths: {
    home: '/en',
    clinic: '/en/clinic',
    team: '/en/team',
    partners: '/en/getting-involved',
    contact: '/en/contact',
    donate: '/en/getting-involved',
    schedule: '/en/schedule',
    scheduleLookup: '/en/schedule/lookup',
    privacy: '/en/privacy',
    splash: '/en',
  },
  nav: [
    { id: 'home', label: 'Home', to: '/en' },
    { id: 'team', label: 'Our Team', to: '/en/team' },
    { id: 'clinic', label: 'The Clinic', to: '/en/clinic' },
    { id: 'book', label: 'Book Now', to: '/en/schedule' },
    { id: 'donate', label: 'Getting Involved', to: '/en/getting-involved' },
  ],
  splash: {
    title: 'LASA Medical Foundation',
    mission:
      'LASA Medical Foundation is a Massachusetts-based nonprofit that provides free and low-cost, volunteer-driven healthcare to underserved populations, with no service contingent on a patient’s ability to pay or insurance status.',
    phoneLabel: 'Phone',
    enterEnglish: 'Click here to enter English website',
    enterSpanish: 'Oprima aquí para español',
  },
  about: {
    title: 'Home',
    lede: 'Love All, Serve All.',
    welcomeKicker: 'Welcome to',
    welcomeName: 'LASA Medical Foundation',
    primaryCta: 'Book Now',
    secondaryCta: 'Getting Involved',
    teamCta: 'Our Team',
    paragraphs: [
      'LASA Medical Foundation is a Massachusetts-based 501(c)(3) nonprofit organized to provide free and low-cost healthcare to underserved people through a volunteer-driven clinic. No service is contingent on a patient’s ability to pay or insurance status.',
      'The clinic offers non-emergency primary care for acute and chronic conditions. Volunteer physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and community members staff each clinic day without salaries, so as much support as possible goes to patient care.',
      'Many of those volunteers come from the Lowell community we serve. “Love All, Serve All” is both our motto and the way the clinic operates: people give their time because they want neighbors to have a place to turn for care.',
    ],
  },
  team: {
    title: 'Our Team',
    lede: 'The clinic is led by a volunteer board, medical director, and administrator, with visiting clinicians on each clinic day.',
    boardTitle: 'Board Members',
    board: [
      {
        name: 'Dr. Anasuya Gunturi, MD, PhD',
        bio: 'A triple-boarded physician in Internal Medicine, Hematology, and Medical Oncology who serves as the Chief of Oncology and Medical Director of the Cancer Center at Tufts Medicine Lowell General Hospital. She is also on the Board of Trustees for Tufts Medicine Lowell General Hospital.',
      },
      {
        name: 'Dr. Suman Koganti, MD',
        bio: 'A board-certified Hepato-Biliary and Pancreatic (HPB) surgeon. He serves as Clinical Assistant Professor of Surgery at Tufts Medical Center and Medical Director of HPB Surgery at Lowell General Hospital.',
      },
      {
        name: 'Dr. Swapna Putta, MD',
        bio: 'A board-certified neurologist based in South Weymouth, Massachusetts, who specializes in epilepsy and neurophysiology. She serves as the Director of the EEG laboratory at South Shore Hospital and is affiliated with Mass General Brigham and Brigham and Women’s Hospital.',
      },
      {
        name: 'Ramesh Razdan',
        bio: 'A seasoned corporate executive who currently serves as the Chief Information Officer of Bain & Company.',
      },
      {
        name: 'Dr. Sanjay Shah, MD',
        bio: 'A board-certified cardiologist practicing in Weymouth, MA at South Shore Cardiology and UMass Memorial Medical Center. He is affiliated with Milford Regional Medical Center and UMass Memorial Health.',
      },
    ],
    operationsTitle: 'Clinic Operations',
    leadership: [
      {
        role: 'Medical Director',
        name: 'Dr. Usha Rallapalli, MD',
        bio: 'A board-certified Family physician who works at Reliant Medical, Optum Care.',
      },
      {
        role: 'Clinic Administrator',
        name: 'Vijay Sarathy',
        bio: 'A seasoned corporate executive who currently serves as a Senior Advisor with McKinsey & Company.',
      },
    ],
    back: 'Back to Home',
  },
  partners: {
    title: 'Our Partners',
    lede: 'We thank our partners for supporting clinic operations.',
    memberTitle: 'Membership',
    memberIntro: 'We are a member of the National Association of Free & Charitable Clinics.',
  },
  hours: {
    title: 'Hours',
    intro:
      'Standing remote and in-person hours will be posted here as they are confirmed. Specific upcoming clinic days are listed on the schedule.',
    rows: [
      { label: 'Remote by phone', value: 'To be confirmed' },
      { label: 'In-person', value: 'To be confirmed' },
    ],
    scheduleIntro: 'See published clinic days and claim a limited spot.',
    scheduleCta: 'Book a clinic day',
  },
  donate: {
    title: 'Getting Involved',
    lede: 'Support the clinic through a gift, your time, supplies, or a community partnership.',
    button: 'Getting Involved',
    donation: {
      title: 'Make a Donation',
      body: 'Your gift helps volunteer clinicians provide free care in Lowell.',
      button: 'Donate',
      note: 'PayPal checkout will be connected here next.',
      disclaimer:
        'LASA Medical Foundation, Inc. is a 501(c)(3) nonprofit public charity. Contributions are tax-deductible to the extent permitted by law.',
    },
    volunteer: {
      title: 'Volunteer',
      body: 'Join volunteer clinicians and community members at the free medical clinic.',
      button: 'Volunteer',
      note: 'A volunteer form will be connected here soon.',
    },
    supplies: {
      title: 'Donate Medical Supplies',
      body: 'To donate medical supplies, contact the Clinic Administrator.',
    },
    partner: {
      title: 'Become a Community Partner',
      body: 'To become a community partner, contact the Clinic Administrator.',
    },
  },
  clinic: {
    heroTitle: 'The Clinic',
    motto: 'Love All, Serve All',
    intro:
      'A volunteer-run clinic offering free primary care to people who are uninsured or cannot afford medical care.',
    subnav: [
      { id: 'services', label: 'Services' },
      { id: 'hours', label: 'Hours' },
      { id: 'location', label: 'Location' },
      { id: 'contact', label: 'Contact' },
      { id: 'privacy', label: 'Privacy' },
      { id: 'schedule', label: 'Schedule' },
      { id: 'donate', label: 'Getting Involved' },
    ],
    paragraphs: [
      'We provide non-emergency care for both acute and chronic medical conditions. The clinic is staffed by volunteer physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and other support staff.',
      'Many of the volunteers who work at our clinic come from the local community that we serve. Highly skilled medical professionals — physicians, nurse practitioners, physician assistants, registered nurses, and physical therapists — volunteer their time at the Clinic.',
    ],
  },
  operate: {
    title: 'How we operate the Clinic',
    paragraphs: [
      'Much of the assistance we need to operate the Clinic is provided by the physicians, nurse practitioners, physician assistants, registered nurses, physical therapists, and all the other support staff who volunteer their time to serve the patients who come to our clinic. We know that the Clinic will be supported by people who of their own accord are moved to provide assistance.',
      'We appreciate all the generosity of our volunteers as well as the many private and institutional donors who make this work possible.',
      'If you would like to help the LASA Medical Foundation Inc. in some way, you can contact us at info@lasamedical.org.',
    ],
  },
  services: {
    title: 'Services',
    intro:
      'Our volunteer physicians and healthcare professionals provide evaluation, treatment, education, and referral for a wide range of common medical conditions.',
    treatTitle: 'Conditions We Treat',
    treat: [
      'High blood pressure (hypertension)',
      'Diabetes and prediabetes',
      'High cholesterol and other lipid disorders',
      'Heart disease and cardiovascular risk factors',
      'Kidney and urinary conditions',
      'Liver, digestive, and gastrointestinal problems',
      'Common neurological conditions',
      'Basic respiratory problems, including asthma and COPD',
      'Musculoskeletal problems and arthritis',
      'Common infections',
      'Mental health concerns',
      'Preventive health and cancer screening',
      'Nutritional and lifestyle-related conditions',
    ],
    cannotTitle: 'Services Outside Our Scope',
    cannot: [
      'Medical emergencies requiring immediate hospital care',
      'Acute chest pain, severe shortness of breath, stroke symptoms, or major bleeding',
      'Severe trauma or life-threatening injuries',
      'Conditions requiring hospitalization or intensive care',
      'Emergency surgery or procedures requiring an operating room',
      'Acute severe psychiatric emergencies, including immediate risk of harm to self or others',
      'Controlled-substance management or chronic opioid / pain-management programs',
      'Emergency obstetric care or delivery',
      'Emergency dental procedures beyond the services specifically offered at the clinic',
      'Specialized diagnostic testing or treatment that is not available through our clinic',
      'Conditions requiring continuous monitoring, specialized equipment, or inpatient services',
    ],
    note: 'If you have a medical emergency, please call 911 or go to the nearest emergency department. Our clinic staff can help direct patients to appropriate medical resources when a condition is outside the scope of our services.',
  },
  location: {
    title: 'Location',
    clinicName: 'LASA Medical Foundation',
    drivingTitle: 'Driving Address',
    mailingTitle: 'Mailing Address',
    phoneLabel: 'Phone',
    directionsTitle: 'Directions',
    directionsIntro:
      'We are located at 40 Old Ferry Road, Lowell, MA 01854. Use the map below for turn-by-turn directions, or open the location in Google Maps or Apple Maps.',
    parkingTitle: 'Parking',
    parking: 'Parking available on-site.',
    openMaps: 'Open in Google Maps',
    openAppleMaps: 'Open in Apple Maps',
  },
  contact: {
    title: 'Contact Us',
    emergency:
      'If you are experiencing a medical or psychiatric emergency, please call 911 or, if possible, go to the Emergency Department nearest to your location.',
    body:
      'You can contact us by calling our main phone number or by sending an email to the address below. For voice mails, please be sure to leave a call-back number and spell out your name clearly. For emails, please include your name, email, phone, subject, and the message. Please be advised that voice mails or emails are NOT reviewed immediately. They will be attended to only on the next clinic day. There will likely be significant delays in getting back to your message.',
    emailLabel: 'Email',
    inquiryLine: 'Reach out for general inquiries.',
  },
  privacyTeaser: {
    title: 'Privacy',
    paragraphs: [
      'Your protected health information (PHI) is health information that contains identifiers, such as your name, Social Security number, or other information that reveals who you are. For example, your medical record is PHI because it includes your name and other identifiers.',
      'By law, we must (1) protect the privacy of your PHI, (2) tell you about your rights and our legal duties with respect to your PHI, and (3) tell you about our privacy practices and follow our notice currently in effect.',
      'We take these responsibilities seriously and will take appropriate steps to safeguard the privacy of your PHI. Read our full Notice of Privacy Practices for details.',
    ],
    cta: 'Privacy Practices',
  },
  privacyPage: privacyPageEn,
  schedulePage: {
    title: 'Schedule',
    comingSoon: 'Coming Soon...',
    intro:
      'Upcoming clinic days are listed below. Capacity is limited. Claiming a spot holds it while you verify your email.',
    empty: 'No upcoming clinic days are published yet.',
    emptyNote: 'Please check back later, or contact us for the latest clinic dates and hours.',
    error: 'The schedule could not be loaded. Please try again shortly.',
    back: 'Back to the clinic',
    backToList: 'All clinic days',
    lookupCta: 'Check a booking',
    spots: '{n} of {total} spots left',
    full: 'This clinic day is fully booked',
    alreadyBooked: 'This email already has a booking for this clinic day.',
    details: 'View details',
    bookTitle: 'Claim a spot',
    emailLabel: 'Email',
    sendCode: 'Send verification code',
    sending: 'Sending code…',
    otpLabel: '6-digit code',
    otpHelp: 'Enter the code we sent to your email. It expires in a few minutes.',
    verify: 'Verify code',
    verifying: 'Verifying…',
    resend: 'Resend code',
    nameLabel: 'Full name',
    phoneLabel: 'Phone',
    consentLabel:
      'I consent to LASA Medical Foundation storing this contact information to complete my clinic booking.',
    confirmSpot: 'Confirm booking',
    confirming: 'Confirming…',
    successTitle: 'Your spot is confirmed',
    confirmationLabel: 'Confirmation code',
    emailSent: 'A confirmation email is on the way.',
    emailFailed: 'Your booking is confirmed, but the confirmation email could not be sent. Save this code.',
    holdNote: 'This hold expires at {time}. Finish the steps below to keep the spot.',
    notFound: 'This clinic day is not available.',
    lookupTitle: 'Check your booking',
    lookupIntro: 'Enter the confirmation code and the email used to book.',
    codeLookupLabel: 'Confirmation code',
    findBooking: 'Find booking',
    looking: 'Looking up…',
    lookupMissing: 'No matching confirmed booking was found.',
    statusLabel: 'Status',
    patientLabel: 'Name',
    eventLabel: 'Clinic day',
  },
  footer: {
    linksTitle: 'Quick Links',
    donateIntro: 'Give, volunteer, donate supplies, or partner with the clinic.',
    legal:
      'LASA Medical Foundation is a federally recognized 501(c)(3) non-profit organization. EIN: 42-2270643',
  },
};
