import { privacyPageEs } from './privacyNoticeEs';

export const es = {
  lang: 'es',
  otherLang: 'en',
  otherLangLabel: 'English',
  otherLangPath: '/en',
  siteName: 'LASA Medical Foundation',
  shortName: 'LASA Medical Foundation',
  motto: 'Ama a todos, Sirve a todos',
  paths: {
    home: '/es',
    clinic: '/es/clinica',
    team: '/es/equipo',
    contact: '/es/contacto',
    donate: '/es/donar',
    schedule: '/es/horario',
    scheduleLookup: '/es/horario/consulta',
    privacy: '/es/privacidad',
    splash: '/',
  },
  nav: [
    { id: 'about', label: 'Quiénes somos', to: '/es' },
    { id: 'clinic', label: 'Clínica', to: '/es/clinica' },
    { id: 'book', label: 'Reservar', to: '/es/horario' },
    { id: 'contact', label: 'Contáctenos', to: '/es/contacto' },
    { id: 'donate', label: 'Contribuir a LMF', to: '/es/donar', emphasize: true },
  ],
  splash: {
    title: 'LASA Medical Foundation',
    mission:
      'LASA Medical Foundation es una organización sin fines de lucro con sede en Massachusetts que brinda atención médica gratuita y de bajo costo, impulsada por voluntarios, a poblaciones desatendidas, sin que ningún servicio dependa de la capacidad de pago ni del estado de seguro del paciente.',
    phoneLabel: 'Teléfono',
    enterEnglish: 'Click here to enter English website',
    enterSpanish: 'Oprima aquí para español',
  },
  about: {
    title: 'Quiénes somos',
    lede: 'Ama a todos, Sirve a todos.',
    teamCta: 'Conozca al equipo',
    paragraphs: [
      'LASA Medical Foundation es una organización 501(c)(3) con sede en Massachusetts creada para brindar atención médica gratuita y de bajo costo a personas desatendidas mediante una clínica impulsada por voluntarios. Ningún servicio depende de la capacidad de pago ni del estado de seguro del paciente.',
      'La clínica ofrece atención primaria que no es de emergencia para afecciones agudas y crónicas. Médicos voluntarios, enfermeras practicantes, asistentes médicos, enfermeras registradas, fisioterapeutas y miembros de la comunidad atienden cada día de clínica sin salario, para que el mayor apoyo posible llegue a los pacientes.',
      'Muchos de esos voluntarios provienen de la comunidad de Lowell a la que servimos. “Amar a todos, servir a todos” es nuestro lema y la forma en que opera la clínica: las personas ofrecen su tiempo para que los vecinos tengan un lugar donde recibir atención.',
      'Agradecemos a cada clínico, colaborador y aliado que mantiene las puertas abiertas. Si desea ayudar, puede escribirnos a info@lasamedical.org o usar la página Contribuir.',
    ],
  },
  team: {
    title: 'Conozca al equipo',
    lede: 'La clínica está dirigida por una junta voluntaria, un director médico y un administrador, con clínicos visitantes en cada día de consulta.',
    boardTitle: 'Miembros de la Junta',
    board: [
      'Ramesh Razdan',
      'Dr. Suman Koganti, MD',
      'Dr. Anasuya Gunturi, MD',
      'Dr. Swapna Putta, MD',
      'Dr. Sanjay Shah, MD',
    ],
    leadership: [
      { role: 'Directora médica', name: 'Dr. Usha Rallapalli' },
      { role: 'Administrador de la clínica', name: 'Vijay Sarathy' },
    ],
    thanksTitle: 'Con gratitud',
    thanksIntro: 'Agradecemos a nuestros aliados por apoyar las operaciones de la clínica.',
    memberOf: 'Somos miembros de',
    back: 'Volver a Quiénes somos',
  },
  hours: {
    title: 'Horario',
    intro:
      'Los horarios fijos remotos y presenciales se publicarán aquí cuando se confirmen. Los próximos días de clínica aparecen en la reserva.',
    rows: [
      { label: 'Remoto por teléfono', value: 'Por confirmar' },
      { label: 'En persona', value: 'Por confirmar' },
    ],
    scheduleIntro: 'Vea los días de clínica publicados y reserve un cupo limitado.',
    scheduleCta: 'Reservar un día de clínica',
  },
  donate: {
    title: 'Contribuir a LMF',
    lede: 'Apoye la clínica con un donativo, su tiempo, suministros o una alianza comunitaria.',
    button: 'Contribuir',
    donation: {
      title: 'Hacer un donativo',
      body: 'Su donativo ayuda a que clínicos voluntarios brinden atención gratuita en Lowell.',
      button: 'Donar',
      note: 'El pago por PayPal se conectará aquí después.',
    },
    volunteer: {
      title: 'Ser voluntario',
      body: 'Únase a clínicos y miembros de la comunidad en la clínica médica gratuita.',
      button: 'Voluntariado',
      note: 'Pronto se conectará aquí un formulario de voluntariado.',
    },
    supplies: {
      title: 'Donar suministros médicos',
      body: 'Para donar suministros médicos, comuníquese con Vijay Sarathy, administrador de la clínica.',
    },
    partner: {
      title: 'Ser aliado comunitario',
      body: 'Para ser aliado comunitario, comuníquese con Vijay Sarathy, administrador de la clínica.',
    },
  },
  clinic: {
    heroTitle: 'La Clínica',
    motto: 'Ama a todos, Sirve a todos',
    intro:
      'Una clínica impulsada por voluntarios que ofrece atención primaria gratuita a personas sin seguro o que no pueden pagar la atención médica.',
    subnav: [
      { id: 'services', label: 'Servicios' },
      { id: 'hours', label: 'Horario' },
      { id: 'location', label: 'Ubicación' },
      { id: 'contact', label: 'Contacto' },
      { id: 'privacy', label: 'Privacidad' },
      { id: 'schedule', label: 'Reservar' },
      { id: 'donate', label: 'Contribuir' },
    ],
    paragraphs: [
      'Brindamos atención que no es de emergencia para afecciones médicas agudas y crónicas. La clínica cuenta con médicos voluntarios, enfermeras practicantes, asistentes médicos, enfermeras registradas, fisioterapeutas y otro personal de apoyo.',
      '"Amar a todos, servir a todos" resume los principios operativos de nuestra clínica. Estamos agradecidos por la oportunidad de brindar atención médica gratuita a quienes la necesitan.',
      'Lasa Medical Foundation Inc. es una organización sin fines de lucro 501(c)(3). Para mantener los gastos lo más bajos posible, no tenemos empleados asalariados en la clínica médica. Todos los que trabajan en esta clínica lo hacen como voluntarios no remunerados.',
      'Muchos de los maravillosos voluntarios que trabajan en nuestra clínica provienen de la comunidad local a la que servimos. Profesionales médicos altamente calificados — médicos, enfermeras practicantes, asistentes médicos, enfermeras registradas y fisioterapeutas — ofrecen su tiempo junto a miembros de la comunidad que comparten el compromiso de LASA de Amar a todos, Servir a todos.',
    ],
  },
  operate: {
    title: 'Cómo operamos la Clínica',
    paragraphs: [
      'Gran parte de la asistencia que necesitamos para operar la Clínica la brindan los médicos, las enfermeras practicantes, los asistentes médicos, las enfermeras tituladas, los fisioterapeutas y todo el resto del personal de apoyo, que ofrecen su tiempo como voluntarios para atender a los pacientes que acuden a nuestra clínica. Sabemos que la Clínica contará con el apoyo de personas que por su propia voluntad se movilizan para brindar asistencia.',
      'Agradecemos toda la generosidad de todos nuestros voluntarios, así como de los numerosos donantes privados e institucionales que hacen posible este trabajo.',
      'Si desea ayudar a Lasa Medical Foundation Inc. de alguna manera, puede contactarnos en info@lasamedical.org.',
    ],
  },
  services: {
    title: 'Servicios',
    intro:
      'Lasa Medical Foundation Inc. brinda servicios de atención primaria que no son de urgencia ni de emergencia para personas sin seguro que no pueden pagar el costo de la atención médica. Ofrecemos visitas remotas por teléfono o video y visitas presenciales según el horario de la clínica. Los servicios de fisioterapia, optometría, salud mental y referencias dentales pueden estar disponibles en días seleccionados. Consulte el horario de la clínica para obtener más detalles.',
    treatTitle: 'Ejemplos de algunas condiciones que tratamos',
    treat: [
      'Diabetes',
      'Dolor de garganta / Tos / Resfriado / Gripe',
      'Infecciones de oído / Impactos de cera (cerumen) en los oídos',
      'Condiciones de la piel',
      'Infecciones de orina / vejiga',
      'Presión arterial alta / colesterol alto',
      'Acidez',
      'Niños con afecciones dermatológicas y otorrinolaringológicas (oído, nariz, garganta)',
      'Condiciones de salud mental como estrés, depresión y ansiedad',
      'Condiciones de la vista / Exámenes de la vista para prescripciones',
      'Terapia física',
      'Cuidado dental: preventivo y problemas que afectan la salud general',
    ],
    cannotTitle: 'Ejemplos de condiciones que no podemos tratar',
    cannot: [
      'Procedimientos de emergencia de cualquier tipo',
      'Traumatismos o lesiones que necesitan radiografías',
      'Problemas de sangrado',
      'Vacunas, prueba de tuberculosis (bacilo de la tuberculosis), obstetricia y ginecología',
      'Discapacidad, DMV, formularios de autorización de examen físico, formularios de seguro',
      'Pacientes que necesitan laboratorios urgentes',
      'Condiciones que requieren imágenes: MRI / CT',
      'Papanicolau',
      'ETS / ITS — remita a estos pacientes a Planned Parenthood o al Departamento de Salud del condado',
      'Detección de ETS',
    ],
  },
  location: {
    title: 'Ubicación',
    clinicName: 'LASA Medical Foundation',
    drivingTitle: 'Dirección',
    mailingTitle: 'Dirección postal',
    phoneLabel: 'Teléfono',
    directionsTitle: 'Direcciones',
    directionsIntro:
      'Estamos ubicados en 40 Old Ferry Road, Lowell, MA 01854. Use el mapa a continuación para obtener indicaciones paso a paso, o abra la ubicación en Google Maps o Apple Maps.',
    parkingTitle: 'Estacionamiento',
    parking: 'Estacionamiento disponible en el lugar.',
    openMaps: 'Abrir en Google Maps',
    openAppleMaps: 'Abrir en Apple Maps',
  },
  contact: {
    title: 'Contáctenos',
    emergency:
      'Si tiene una emergencia médica o psiquiátrica, llame al 911 o, si es posible, diríjase al Departamento de Emergencias más cercano a su ubicación.',
    body:
      'Puede contactarnos llamando a nuestro número de teléfono principal o enviando un correo electrónico a la dirección que aparece a continuación. Para los mensajes de voz, asegúrese de dejar un número para que le devolvamos la llamada y escriba su nombre con claridad. Para los correos electrónicos, incluya su nombre, correo electrónico, teléfono, asunto y el mensaje. Tenga en cuenta que los mensajes de voz o correos electrónicos no se revisan de inmediato. Solo se atenderán el siguiente día de consulta. Es probable que haya demoras significativas en responder a su mensaje.',
    emailLabel: 'Correo electrónico',
    inquiryLine: 'Escríbanos para consultas generales.',
  },
  privacyTeaser: {
    title: 'Privacidad',
    paragraphs: [
      'Su Información Privada de Salud (IPS) es la información de salud que contiene identificación, como su nombre, número de seguro social, u otra información que revela quién es. Por ejemplo, su historial médico es IPS porque contiene su nombre y otros medios de identificación.',
      'Por ley, debemos (1) proteger la privacidad de su IPS, (2) advertirle de sus derechos y nuestros deberes legales con respecto a su IPS, y (3) advertirle sobre nuestras prácticas de privacidad y seguir el aviso vigente.',
      'Nos tomamos en serio estas responsabilidades y tomaremos las medidas adecuadas para salvaguardar la privacidad de su IPS.',
    ],
    cta: 'Prácticas de privacidad',
  },
  privacyPage: privacyPageEs,
  schedulePage: {
    title: 'Horario',
    comingSoon: 'Próximamente...',
    intro:
      'Los próximos días de clínica aparecen a continuación. El cupo es limitado. Al reservar se guarda un lugar mientras verifica su correo.',
    empty: 'Aún no hay días de clínica publicados.',
    emptyNote: 'Vuelva a consultar más tarde, o contáctenos para conocer las fechas y horarios más recientes.',
    error: 'No se pudo cargar el horario. Inténtelo de nuevo en un momento.',
    back: 'Volver a la clínica',
    backToList: 'Todos los días de clínica',
    lookupCta: 'Consultar una reserva',
    spots: '{n} de {total} cupos disponibles',
    full: 'Este día de clínica está completo',
    alreadyBooked: 'Este correo ya tiene una reserva para este día de clínica.',
    details: 'Ver detalles',
    bookTitle: 'Reservar un cupo',
    emailLabel: 'Correo electrónico',
    sendCode: 'Enviar código de verificación',
    sending: 'Enviando código…',
    otpLabel: 'Código de 6 dígitos',
    otpHelp: 'Ingrese el código que enviamos a su correo. Caduca en unos minutos.',
    verify: 'Verificar código',
    verifying: 'Verificando…',
    resend: 'Reenviar código',
    nameLabel: 'Nombre completo',
    phoneLabel: 'Teléfono',
    consentLabel:
      'Doy mi consentimiento para que LASA Medical Foundation conserve esta información de contacto y complete mi reserva.',
    confirmSpot: 'Confirmar reserva',
    confirming: 'Confirmando…',
    successTitle: 'Su cupo está confirmado',
    confirmationLabel: 'Código de confirmación',
    emailSent: 'Le enviaremos un correo de confirmación.',
    emailFailed:
      'Su reserva está confirmada, pero no se pudo enviar el correo. Guarde este código.',
    holdNote: 'Esta reserva temporal vence a las {time}. Complete los pasos para conservar el cupo.',
    notFound: 'Este día de clínica no está disponible.',
    lookupTitle: 'Consultar su reserva',
    lookupIntro: 'Ingrese el código de confirmación y el correo usado para reservar.',
    codeLookupLabel: 'Código de confirmación',
    findBooking: 'Buscar reserva',
    looking: 'Buscando…',
    lookupMissing: 'No se encontró una reserva confirmada coincidente.',
    statusLabel: 'Estado',
    patientLabel: 'Nombre',
    eventLabel: 'Día de clínica',
  },
  footer: {
    linksTitle: 'Enlaces',
    donateIntro: 'Done, sea voluntario, aporte suministros o aliése con la clínica.',
    legal:
      'Lasa Medical Foundation es una organización sin fines de lucro 501(c)(3) reconocida a nivel federal. EIN: 42-2270643',
  },
};
