import { privacyPageEs } from './privacyNoticeEs';

export const es = {
  lang: 'es',
  otherLang: 'en',
  otherLangLabel: 'English',
  otherLangPath: '/en',
  siteName: 'LASA Medical Foundation',
  shortName: 'LASA Medical Foundation',
  motto: 'Ama a todos, Sirve a todos',
  paths: {
    home: '/es',
    clinic: '/es/clinica',
    team: '/es/equipo',
    partners: '/es/involucrate',
    contact: '/es/contacto',
    donate: '/es/involucrate',
    schedule: '/es/horario',
    scheduleLookup: '/es/horario/consulta',
    privacy: '/es/privacidad',
    splash: '/es',
  },
  nav: [
    { id: 'home', label: 'Inicio', to: '/es' },
    { id: 'team', label: 'Nuestro equipo', to: '/es/equipo' },
    { id: 'clinic', label: 'La Clínica', to: '/es/clinica' },
    { id: 'book', label: 'Reservar ahora', to: '/es/horario' },
    { id: 'donate', label: 'Involúcrate', to: '/es/involucrate' },
    { id: 'contact', label: 'Contáctenos', to: '/es/contacto' },
  ],
  splash: {
    title: 'LASA Medical Foundation',
    mission:
      'LASA Medical Foundation es una organización sin fines de lucro con sede en Massachusetts que brinda atención médica gratuita y de bajo costo, impulsada por voluntarios, a poblaciones desatendidas, sin que ningún servicio dependa de la capacidad de pago ni del estado de seguro del paciente.',
    phoneLabel: 'Teléfono',
    enterEnglish: 'Click here to enter English website',
    enterSpanish: 'Oprima aquí para español',
  },
  about: {
    title: 'Inicio',
    lede: 'Ama a todos, Sirve a todos.',
    welcomeKicker: 'Bienvenido a',
    welcomeName: 'LASA Medical Foundation',
    primaryCta: 'Reservar ahora',
    secondaryCta: 'Involúcrate',
    teamCta: 'Nuestro equipo',
    paragraphs: [
      'LASA Medical Foundation es una organización 501(c)(3) con sede en Massachusetts creada para brindar atención médica gratuita y de bajo costo a personas desatendidas mediante una clínica impulsada por voluntarios. Ningún servicio depende de la capacidad de pago ni del estado de seguro del paciente.',
      'La clínica ofrece atención primaria que no es de emergencia para afecciones agudas y crónicas. Médicos voluntarios, enfermeras practicantes, asistentes médicos, enfermeras registradas, fisioterapeutas y miembros de la comunidad atienden cada día de clínica sin salario, para que el mayor apoyo posible llegue a los pacientes.',
      'Muchos de esos voluntarios provienen de la comunidad de Lowell a la que servimos. “Amar a todos, servir a todos” es nuestro lema y la forma en que opera la clínica: las personas ofrecen su tiempo para que los vecinos tengan un lugar donde recibir atención.',
    ],
  },
  team: {
    title: 'Nuestro equipo',
    lede: 'La clínica está dirigida por una junta voluntaria, un director médico y un administrador, con clínicos visitantes en cada día de consulta.',
    boardTitle: 'Miembros de la Junta',
    board: [
      {
        name: 'Dr. Anasuya Gunturi, MD, PhD',
        bio: 'Médica con triple certificación en Medicina Interna, Hematología y Oncología Médica. Es jefa de Oncología y directora médica del Centro de Cáncer de Tufts Medicine Lowell General Hospital. También forma parte de la Junta de Fideicomisarios de Tufts Medicine Lowell General Hospital.',
      },
      {
        name: 'Dr. Suman Koganti, MD',
        bio: 'Cirujano hepatobiliar y pancreático (HPB) certificado. Es profesor clínico asistente de cirugía en Tufts Medical Center y director médico de cirugía HPB en Lowell General Hospital.',
      },
      {
        name: 'Dr. Swapna Putta, MD',
        bio: 'Neuróloga certificada en South Weymouth, Massachusetts, especializada en epilepsia y neurofisiología. Es directora del laboratorio de EEG de South Shore Hospital y está afiliada a Mass General Brigham y Brigham and Women’s Hospital.',
      },
      {
        name: 'Ramesh Razdan',
        bio: 'Ejecutivo corporativo con amplia trayectoria que actualmente se desempeña como Director de Información (CIO) de Bain & Company.',
      },
      {
        name: 'Dr. Sanjay Shah, MD',
        bio: 'Cardiólogo certificado que ejerce en Weymouth, MA, en South Shore Cardiology y UMass Memorial Medical Center. Está afiliado a Milford Regional Medical Center y UMass Memorial Health.',
      },
    ],
    operationsTitle: 'Operaciones de la clínica',
    leadership: [
      {
        role: 'Directora médica',
        name: 'Dr. Usha Rallapalli, MD',
        bio: 'Médica de familia certificada. Trabaja en Reliant Medical, Optum Care.',
      },
      {
        role: 'Administrador de la clínica',
        name: 'Vijay Sarathy',
        bio: 'Ejecutivo corporativo con amplia trayectoria que actualmente se desempeña como asesor sénior en McKinsey & Company.',
      },
    ],
    back: 'Volver a Inicio',
  },
  partners: {
    title: 'Nuestros aliados',
    lede: 'Agradecemos a nuestros aliados por apoyar las operaciones de la clínica.',
    memberTitle: 'Membresía',
    memberIntro: 'Somos miembros de la National Association of Free & Charitable Clinics.',
  },
  hours: {
    title: 'Horario',
    intro:
      'Los horarios fijos remotos y presenciales se publicarán aquí cuando se confirmen. Los próximos días de clínica aparecen en la reserva.',
    rows: [
      { label: 'Remoto por teléfono', value: 'Por confirmar' },
      { label: 'En persona', value: 'Por confirmar' },
    ],
    scheduleIntro: 'Vea los días de clínica publicados y reserve un cupo limitado.',
    scheduleCta: 'Reservar un día de clínica',
  },
  donate: {
    title: 'Involúcrate',
    lede: 'Apoye la clínica con un donativo, su tiempo, suministros o una alianza comunitaria.',
    button: 'Involúcrate',
    donation: {
      title: 'Hacer un donativo',
      body: 'Su donativo ayuda a que clínicos voluntarios brinden atención gratuita en Lowell.',
      button: 'Donar',
      note: 'El pago por PayPal se conectará aquí después.',
      disclaimer:
        'LASA Medical Foundation, Inc. es una organización benéfica pública 501(c)(3) sin fines de lucro. Las contribuciones son deducibles de impuestos en la medida permitida por la ley.',
    },
    volunteer: {
      title: 'Ser voluntario',
      body: 'Únase a clínicos y miembros de la comunidad en la clínica médica gratuita.',
      button: 'Voluntariado',
      note: 'Pronto se conectará aquí un formulario de voluntariado.',
    },
    supplies: {
      title: 'Donar suministros médicos',
      body: 'Para donar suministros médicos, comuníquese con el administrador de la clínica.',
    },
    partner: {
      title: 'Ser aliado comunitario',
      body: 'Para ser aliado comunitario, comuníquese con el administrador de la clínica.',
    },
  },
  clinic: {
    heroTitle: 'La Clínica',
    motto: 'Ama a todos, Sirve a todos',
    intro:
      'Una clínica impulsada por voluntarios que ofrece atención primaria gratuita a personas sin seguro o que no pueden pagar la atención médica.',
    subnav: [
      { id: 'services', label: 'Servicios' },
      { id: 'hours', label: 'Horario' },
      { id: 'location', label: 'Ubicación' },
      { id: 'contact', label: 'Contacto' },
      { id: 'privacy', label: 'Privacidad' },
      { id: 'schedule', label: 'Reservar' },
      { id: 'donate', label: 'Involúcrate' },
    ],
    paragraphs: [
      'Brindamos atención que no es de emergencia para afecciones médicas agudas y crónicas. La clínica cuenta con médicos voluntarios, enfermeras practicantes, asistentes médicos, enfermeras registradas, fisioterapeutas y otro personal de apoyo.',
      'Muchos de los voluntarios que trabajan en nuestra clínica provienen de la comunidad local a la que servimos. Profesionales médicos altamente calificados — médicos, enfermeras practicantes, asistentes médicos, enfermeras registradas y fisioterapeutas — ofrecen su tiempo en la Clínica.',
    ],
  },
  operate: {
    title: 'Cómo operamos la Clínica',
    paragraphs: [
      'Gran parte de la asistencia que necesitamos para operar la Clínica la brindan los médicos, las enfermeras practicantes, los asistentes médicos, las enfermeras tituladas, los fisioterapeutas y todo el resto del personal de apoyo, que ofrecen su tiempo como voluntarios para atender a los pacientes que acuden a nuestra clínica. Sabemos que la Clínica contará con el apoyo de personas que por su propia voluntad se movilizan para brindar asistencia.',
      'Agradecemos toda la generosidad de todos nuestros voluntarios, así como de los numerosos donantes privados e institucionales que hacen posible este trabajo.',
      'Si desea ayudar a LASA Medical Foundation Inc. de alguna manera, puede contactarnos en info@lasamedical.org.',
    ],
  },
  services: {
    title: 'Servicios',
    intro:
      'Nuestros médicos voluntarios y profesionales de la salud ofrecen evaluación, tratamiento, educación y referencias para una amplia gama de afecciones médicas comunes.',
    treatTitle: 'Afecciones que tratamos',
    treat: [
      'Presión arterial alta (hipertensión)',
      'Diabetes y prediabetes',
      'Colesterol alto y otros trastornos de lípidos',
      'Enfermedad cardíaca y factores de riesgo cardiovascular',
      'Afecciones renales y urinarias',
      'Problemas hepáticos, digestivos y gastrointestinales',
      'Afecciones neurológicas comunes',
      'Problemas respiratorios básicos, incluyendo asma y EPOC',
      'Problemas musculoesqueléticos y artritis',
      'Infecciones comunes',
      'Preocupaciones de salud mental',
      'Salud preventiva y detección de cáncer',
      'Afecciones nutricionales y relacionadas con el estilo de vida',
    ],
    cannotTitle: 'Servicios fuera de nuestro alcance',
    cannot: [
      'Emergencias médicas que requieren atención hospitalaria inmediata',
      'Dolor torácico agudo, falta de aire grave, síntomas de accidente cerebrovascular o hemorragia mayor',
      'Traumatismos graves o lesiones que ponen en peligro la vida',
      'Afecciones que requieren hospitalización o cuidados intensivos',
      'Cirugía de emergencia o procedimientos que requieren un quirófano',
      'Emergencias psiquiátricas agudas graves, incluido el riesgo inmediato de daño a sí mismo o a otros',
      'Manejo de sustancias controladas o programas crónicos de opioides / manejo del dolor',
      'Atención obstétrica de emergencia o parto',
      'Procedimientos dentales de emergencia más allá de los servicios que ofrece específicamente la clínica',
      'Pruebas diagnósticas especializadas o tratamientos que no están disponibles en nuestra clínica',
      'Afecciones que requieren monitoreo continuo, equipo especializado o servicios hospitalarios',
    ],
    note: 'Si tiene una emergencia médica, llame al 911 o acuda al departamento de emergencias más cercano. El personal de la clínica puede orientar a los pacientes hacia los recursos médicos adecuados cuando una afección está fuera del alcance de nuestros servicios.',
  },
  location: {
    title: 'Ubicación',
    clinicName: 'LASA Medical Foundation',
    drivingTitle: 'Dirección',
    mailingTitle: 'Dirección postal',
    phoneLabel: 'Teléfono',
    directionsTitle: 'Direcciones',
    directionsIntro:
      'Estamos ubicados en 40 Old Ferry Road, Lowell, MA 01854. Use el mapa a continuación para obtener indicaciones paso a paso, o abra la ubicación en Google Maps o Apple Maps.',
    parkingTitle: 'Estacionamiento',
    parking: 'Estacionamiento disponible en el lugar.',
    openMaps: 'Abrir en Google Maps',
    openAppleMaps: 'Abrir en Apple Maps',
  },
  contact: {
    title: 'Contáctenos',
    emergency:
      'Si tiene una emergencia médica o psiquiátrica, llame al 911 o, si es posible, diríjase al Departamento de Emergencias más cercano a su ubicación.',
    body:
      'Puede contactarnos llamando a nuestro número de teléfono principal o enviando un correo electrónico a la dirección que aparece a continuación. Para los mensajes de voz, asegúrese de dejar un número para que le devolvamos la llamada y escriba su nombre con claridad. Para los correos electrónicos, incluya su nombre, correo electrónico, teléfono, asunto y el mensaje. Tenga en cuenta que los mensajes de voz o correos electrónicos no se revisan de inmediato. Solo se atenderán el siguiente día de consulta. Es probable que haya demoras significativas en responder a su mensaje.',
    emailLabel: 'Correo electrónico',
    inquiryLine: 'Escríbanos para consultas generales.',
  },
  privacyTeaser: {
    title: 'Privacidad',
    paragraphs: [
      'Su Información Privada de Salud (IPS) es la información de salud que contiene identificación, como su nombre, número de seguro social, u otra información que revela quién es. Por ejemplo, su historial médico es IPS porque contiene su nombre y otros medios de identificación.',
      'Por ley, debemos (1) proteger la privacidad de su IPS, (2) advertirle de sus derechos y nuestros deberes legales con respecto a su IPS, y (3) advertirle sobre nuestras prácticas de privacidad y seguir el aviso vigente.',
      'Nos tomamos en serio estas responsabilidades y tomaremos las medidas adecuadas para salvaguardar la privacidad de su IPS.',
    ],
    cta: 'Prácticas de privacidad',
  },
  privacyPage: privacyPageEs,
  schedulePage: {
    title: 'Horario',
    comingSoon: 'Próximamente...',
    intro:
      'Los próximos días de clínica aparecen a continuación. El cupo es limitado. Al reservar se guarda un lugar mientras verifica su correo.',
    empty: 'Aún no hay días de clínica publicados.',
    emptyNote: 'Vuelva a consultar más tarde, o contáctenos para conocer las fechas y horarios más recientes.',
    error: 'No se pudo cargar el horario. Inténtelo de nuevo en un momento.',
    back: 'Volver a la clínica',
    backToList: 'Todos los días de clínica',
    lookupCta: 'Consultar una reserva',
    spots: '{n} de {total} cupos disponibles',
    full: 'Este día de clínica está completo',
    alreadyBooked: 'Este correo ya tiene una reserva para este día de clínica.',
    details: 'Ver detalles',
    bookTitle: 'Reservar un cupo',
    emailLabel: 'Correo electrónico',
    sendCode: 'Enviar código de verificación',
    sending: 'Enviando código…',
    otpLabel: 'Código de 6 dígitos',
    otpHelp: 'Ingrese el código que enviamos a su correo. Caduca en unos minutos.',
    verify: 'Verificar código',
    verifying: 'Verificando…',
    resend: 'Reenviar código',
    nameLabel: 'Nombre completo',
    phoneLabel: 'Teléfono',
    consentLabel:
      'Doy mi consentimiento para que LASA Medical Foundation conserve esta información de contacto y complete mi reserva.',
    confirmSpot: 'Confirmar reserva',
    confirming: 'Confirmando…',
    successTitle: 'Su cupo está confirmado',
    confirmationLabel: 'Código de confirmación',
    emailSent: 'Le enviaremos un correo de confirmación.',
    emailFailed:
      'Su reserva está confirmada, pero no se pudo enviar el correo. Guarde este código.',
    holdNote: 'Esta reserva temporal vence a las {time}. Complete los pasos para conservar el cupo.',
    notFound: 'Este día de clínica no está disponible.',
    lookupTitle: 'Consultar su reserva',
    lookupIntro: 'Ingrese el código de confirmación y el correo usado para reservar.',
    codeLookupLabel: 'Código de confirmación',
    findBooking: 'Buscar reserva',
    looking: 'Buscando…',
    lookupMissing: 'No se encontró una reserva confirmada coincidente.',
    statusLabel: 'Estado',
    patientLabel: 'Nombre',
    eventLabel: 'Día de clínica',
  },
  footer: {
    linksTitle: 'Enlaces',
    donateIntro: 'Done, sea voluntario, aporte suministros o aliése con la clínica.',
    legal:
      'LASA Medical Foundation es una organización sin fines de lucro 501(c)(3) reconocida a nivel federal. EIN: 42-2270643',
  },
};
